### ISSUE TITLE
Can u provide a h5 file to test?

### ISSUE THREAD

**Issue by yyihuan** [vishnubk/5D_Peasoup#2]
I'm trying to use the software, and it may be very useful. But it isn't worked until now.
Always, when I pass through a templates bank file(h5 file) to peasoup, it throws an error.
```
$ ./peasoup -i ../example_data/tutorial.fil -T ../../5D_template_bank.h5
Setting transform length to 131072 points
Tsamp is 0.00031999999191612
Tstart is 50000
Reading template bank file ../../5D_template_bank.h5
Segmentation fault (core dumped)
```
Either using a program that I've compiled myself or your peasoup program in /bin, which you've already compiled with cuda9.0 env, the same error.
I don't know if this is because I used the wrong command or passed the wrong h5 file. So, I would appreciate it if you could provide an h5 file for me to test or point out my usage errors.

**Comment by yyihuan** [comment]
I'm sure the error occurs in the process that new a Templates bank obj. It seems that the -T parameter should accept string files, but my template bank file is bytes. Can u give me some advice?

**Comment by yyihuan** [comment]
I'm sure the error occurs in the process that new a Templates bank obj. It seems that the -T parameter should accept string files, but my template bank file is bytes. Can u give me some advice?

**Comment by vishnubk** [comment]
The template-bank file should be composed of float values. I have now attached an example in the fast_bt_resampler_working_branch. 

Check:
Template Bank Example: [emcee_plot_codes/5D_template_bank_sample](https://github.com/vishnubk/5D_Peasoup/blob/fast_bt_resampler_working/emcee_plot_codes/5D_template_bank_sample)
Regarding generating a template-bank file from a .h5 file, you can find the code for that in 
https://github.com/vishnubk/5D_Peasoup/blob/fast_bt_resampler_working/emcee_plot_codes/generate_elliptical_orbit_search_template_bank_from_h5.py

**Comment by yyihuan** [comment]
Now, It works well. Thank you for your help. I'm going to make a docker image,  and I wonder if you'd mind committing it to your repository？

**Comment by vishnubk** [comment]
sure. :)
